// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using eVote360.Infraestructure.Persistence.Context;

#nullable disable

namespace eVote360.Infraestructure.Persistence.Migrations
{
    [DbContext(typeof(DbContextEVote360))]
    [Migration("20260617001344_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("eVote360.Core.Domain.Entities.Candidate.Candidates", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset?>("CreateAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset(0)")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("CreateUserId")
                        .HasColumnType("int");

                    b.Property<bool>("HasParticipatedInElection")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("PoliticalPartyId")
                        .HasColumnType("int");

                    b.Property<bool>("State")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTimeOffset?>("UpdateAt")
                        .HasColumnType("datetimeoffset(0)");

                    b.Property<int?>("UpdateUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreateUserId");

                    b.HasIndex("PoliticalPartyId");

                    b.HasIndex("UpdateUserId");

                    b.ToTable("Candidates", (string)null);
                });

            modelBuilder.Entity("eVote360.Core.Domain.Entities.CandidateAssignment.CandidateAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AssigningPartyId")
                        .HasColumnType("int");

                    b.Property<int>("CandidateId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreateAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset(0)")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("CreateUserId")
                        .HasColumnType("int");

                    b.Property<int>("ElectivePositionId")
                        .HasColumnType("int");

                    b.Property<int?>("ElectivePositionsId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CandidateId");

                    b.HasIndex("ElectivePositionId");

                    b.HasIndex("ElectivePositionsId");

                    b.HasIndex("AssigningPartyId", "CandidateId")
                        .IsUnique();

                    b.HasIndex("AssigningPartyId", "ElectivePositionId")
                        .IsUnique();

                    b.ToTable("CandidateAssignments", (string)null);
                });

            modelBuilder.Entity("eVote360.Core.Domain.Entities.Citizens.Citizen", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTimeOffset?>("CreateAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("SYSDATETIMEOFFSET()");

                    b.Property<int?>("CreateUserId")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<bool>("State")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTimeOffset?>("UpdateAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("UpdateUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreateUserId");

                    b.HasIndex("UpdateUserId");

                    b.ToTable("Citizens", (string)null);
                });

            modelBuilder.Entity("eVote360.Core.Domain.Entities.Election.Election", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset?>("CreateAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("CreateUserId")
                        .HasColumnType("int");

                    b.Property<int>("ElectionState")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar");

                    b.Property<bool>("State")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTimeOffset?>("UpdateAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("UpdateUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreateUserId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("UpdateUserId");

                    b.ToTable("Elections", (string)null);
                });

            modelBuilder.Entity("eVote360.Core.Domain.Entities.ElectivePosition.ElectivePositions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset?>("CreateAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset(0)")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("CreateUserId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int?>("ElectionId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .UseCollation("Modern_Spanish_CI_AI");

                    b.Property<bool>("State")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTimeOffset?>("UpdateAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset(0)")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int?>("UpdateUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreateUserId");

                    b.HasIndex("ElectionId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("UpdateUserId");

                    b.ToTable("ElectivePosictions", (string)null);
                });

            modelBuilder.Entity("eVote360.Core.Domain.Entities.Elector.AuditVote.AuditVotes", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CitizenId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset(0)")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int?>("ElectionId")
                        .HasColumnType("int");

                    b.Property<Guid>("IdCitizen")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("IdElection")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CitizenId");

                    b.HasIndex("ElectionId");

                    b.HasIndex("IdCitizen");

                    b.HasIndex("IdElection");

                    b.ToTable("AuditVotes", (string)null);
                });

            modelBuilder.Entity("eVote360.Core.Domain.Entities.Elector.CodeVerifications.CodeVerification", b =>
                {
                    b.Property<Guid>("IdCitizens")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("IdElection")
                        .HasColumnType("int");

                    b.Property<int>("Code")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreateAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("SYSDATETIMEOFFSET()");

                    b.Property<DateTimeOffset>("ExpirationDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("State")
                        .HasColumnType("bit");

                    b.HasKey("IdCitizens", "IdElection");

                    b.HasIndex("IdElection");

                    b.ToTable("CodeVerification", (string)null);
                });

            modelBuilder.Entity("eVote360.Core.Domain.Entities.Elector.Vote.Votes", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("CandidatesId")
                        .HasColumnType("int");

                    b.Property<Guid?>("CitizenId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("ElectivePositionsId")
                        .HasColumnType("int");

                    b.Property<int>("IdCandidate")
                        .HasColumnType("int");

                    b.Property<int>("IdElection")
                        .HasColumnType("int");

                    b.Property<int>("IdElectivePosiction")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CandidatesId");

                    b.HasIndex("CitizenId");

                    b.HasIndex("ElectivePositionsId");

                    b.HasIndex("IdCandidate");

                    b.HasIndex("IdElection");

                    b.HasIndex("IdElectivePosiction");

                    b.ToTable("Votes", (string)null);
                });

            modelBuilder.Entity("eVote360.Core.Domain.Entities.PoliticalAlliances.PoliticalAlliances", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreateAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset(0)")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("CreateUserId")
                        .HasColumnType("int");

                    b.Property<int>("ReceivingPartyId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("RequestDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset(0)")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("RequestingPartyId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("ResponseDate")
                        .HasColumnType("datetimeoffset(0)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("Pending");

                    b.HasKey("Id");

                    b.HasIndex("ReceivingPartyId");

                    b.HasIndex("RequestingPartyId");

                    b.ToTable("PoliticalAlliances", (string)null);
                });

            modelBuilder.Entity("eVote360.Core.Domain.Entities.PoliticalAssignment.PoliticalAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset?>("CreateAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("CreateUserId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar");

                    b.Property<DateTime>("PolitcalAssignmentDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PoliticalLeaderId")
                        .HasColumnType("int");

                    b.Property<int>("PoliticalPartyId")
                        .HasColumnType("int");

                    b.Property<bool>("State")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("UpdateAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("UpdateUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreateUserId");

                    b.HasIndex("PoliticalLeaderId");

                    b.HasIndex("PoliticalPartyId");

                    b.HasIndex("UpdateUserId");

                    b.ToTable("PoliticalAssignments", (string)null);
                });

            modelBuilder.Entity("eVote360.Core.Domain.Entities.PoliticalParty.PoliticalParty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset?>("CreateAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("CreateUserId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar");

                    b.Property<string>("PoliticalPartyDescription")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar");

                    b.Property<bool>("State")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTimeOffset?>("UpdateAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("UpdateUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreateUserId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("UpdateUserId");

                    b.ToTable("PoliticalParties", (string)null);
                });

            modelBuilder.Entity("eVote360.Core.Domain.Entities.User.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar")
                        .HasColumnName("Username");

                    b.Property<bool>("State")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("UserFirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar")
                        .HasColumnName("FirstName");

                    b.Property<string>("UserLastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar")
                        .HasColumnName("LastName");

                    b.Property<string>("UserRole")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("eVote360.Core.Domain.Entities.Candidate.Candidates", b =>
                {
                    b.HasOne("eVote360.Core.Domain.Entities.User.User", "UserCreate")
                        .WithMany()
                        .HasForeignKey("CreateUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("eVote360.Core.Domain.Entities.PoliticalParty.PoliticalParty", "Partido")
                        .WithMany("Candidates")
                        .HasForeignKey("PoliticalPartyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("eVote360.Core.Domain.Entities.User.User", "UserUpdate")
                        .WithMany()
                        .HasForeignKey("UpdateUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.OwnsOne("eVote360.Core.Domain.Settings.ValueObjects.Candidate.CandidatePhoto", "PhotoUrl", b1 =>
                        {
                            b1.Property<int>("CandidatesId")
                                .HasColumnType("int");

                            b1.Property<string>("PhotoUrl")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("PhotoUrl");

                            b1.HasKey("CandidatesId");

                            b1.ToTable("Candidates");

                            b1.WithOwner()
                                .HasForeignKey("CandidatesId");
                        });

                    b.OwnsOne("eVote360.Core.Domain.Settings.ValueObjects.Candidate.FullName", "Name", b1 =>
                        {
                            b1.Property<int>("CandidatesId")
                                .HasColumnType("int");

                            b1.Property<string>("LastName")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("LastName");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("FirstName");

                            b1.HasKey("CandidatesId");

                            b1.ToTable("Candidates");

                            b1.WithOwner()
                                .HasForeignKey("CandidatesId");
                        });

                    b.Navigation("Name")
                        .IsRequired();

                    b.Navigation("Partido");

                    b.Navigation("PhotoUrl")
                        .IsRequired();

                    b.Navigation("UserCreate");

                    b.Navigation("UserUpdate");
                });

            modelBuilder.Entity("eVote360.Core.Domain.Entities.CandidateAssignment.CandidateAssignment", b =>
                {
                    b.HasOne("eVote360.Core.Domain.Entities.PoliticalParty.PoliticalParty", "AssigningParty")
                        .WithMany()
                        .HasForeignKey("AssigningPartyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("eVote360.Core.Domain.Entities.Candidate.Candidates", "Candidate")
                        .WithMany("AsignacionesPuestos")
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("eVote360.Core.Domain.Entities.ElectivePosition.ElectivePositions", "ElectivePosition")
                        .WithMany()
                        .HasForeignKey("ElectivePositionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("eVote360.Core.Domain.Entities.ElectivePosition.ElectivePositions", null)
                        .WithMany("CandidateAssignments")
                        .HasForeignKey("ElectivePositionsId");

                    b.Navigation("AssigningParty");

                    b.Navigation("Candidate");

                    b.Navigation("ElectivePosition");
                });

            modelBuilder.Entity("eVote360.Core.Domain.Entities.Citizens.Citizen", b =>
                {
                    b.HasOne("eVote360.Core.Domain.Entities.User.User", "UserCreate")
                        .WithMany()
                        .HasForeignKey("CreateUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("eVote360.Core.Domain.Entities.User.User", "UserUpdate")
                        .WithMany()
                        .HasForeignKey("UpdateUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.OwnsOne("eVote360.Core.Domain.Settings.ValueObjects.Emails.Email", "Email", b1 =>
                        {
                            b1.Property<Guid>("CitizenId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(254)
                                .HasColumnType("nvarchar")
                                .HasColumnName("Email");

                            b1.HasKey("CitizenId");

                            b1.HasIndex("Value")
                                .IsUnique();

                            b1.ToTable("Citizens");

                            b1.WithOwner()
                                .HasForeignKey("CitizenId");
                        });

                    b.OwnsOne("eVote360.Core.Domain.Settings.ValueObjects.Identifications.IdentificationN", "IdentificationNumber", b1 =>
                        {
                            b1.Property<Guid>("CitizenId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(11)
                                .HasColumnType("nvarchar")
                                .HasColumnName("IdentificationNumber");

                            b1.HasKey("CitizenId");

                            b1.HasIndex("Value")
                                .IsUnique();

                            b1.ToTable("Citizens");

                            b1.WithOwner()
                                .HasForeignKey("CitizenId");
                        });

                    b.Navigation("Email")
                        .IsRequired();

                    b.Navigation("IdentificationNumber")
                        .IsRequired();

                    b.Navigation("UserCreate");

                    b.Navigation("UserUpdate");
                });

            modelBuilder.Entity("eVote360.Core.Domain.Entities.Election.Election", b =>
                {
                    b.HasOne("eVote360.Core.Domain.Entities.User.User", "UserCreate")
                        .WithMany()
                        .HasForeignKey("CreateUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("eVote360.Core.Domain.Entities.User.User", "UserUpdate")
                        .WithMany()
                        .HasForeignKey("UpdateUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.OwnsOne("eVote360.Core.Domain.Settings.ValueObjects.ElectionDate.ElectionDate", "ElectionDate", b1 =>
                        {
                            b1.Property<int>("ElectionId")
                                .HasColumnType("int");

                            b1.Property<DateTime>("Value")
                                .HasColumnType("datetime2")
                                .HasColumnName("ElectionDate");

                            b1.HasKey("ElectionId");

                            b1.ToTable("Elections");

                            b1.WithOwner()
                                .HasForeignKey("ElectionId");
                        });

                    b.Navigation("ElectionDate")
                        .IsRequired();

                    b.Navigation("UserCreate");

                    b.Navigation("UserUpdate");
                });

            modelBuilder.Entity("eVote360.Core.Domain.Entities.ElectivePosition.ElectivePositions", b =>
                {
                    b.HasOne("eVote360.Core.Domain.Entities.User.User", "UserCreate")
                        .WithMany()
                        .HasForeignKey("CreateUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("eVote360.Core.Domain.Entities.Election.Election", null)
                        .WithMany("ElectivePositions")
                        .HasForeignKey("ElectionId");

                    b.HasOne("eVote360.Core.Domain.Entities.User.User", "UserUpdate")
                        .WithMany()
                        .HasForeignKey("UpdateUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("UserCreate");

                    b.Navigation("UserUpdate");
                });

            modelBuilder.Entity("eVote360.Core.Domain.Entities.Elector.AuditVote.AuditVotes", b =>
                {
                    b.HasOne("eVote360.Core.Domain.Entities.Citizens.Citizen", null)
                        .WithMany("AuditVote")
                        .HasForeignKey("CitizenId");

                    b.HasOne("eVote360.Core.Domain.Entities.Election.Election", null)
                        .WithMany("AuditVotes")
                        .HasForeignKey("ElectionId");

                    b.HasOne("eVote360.Core.Domain.Entities.Citizens.Citizen", "Citizens")
                        .WithMany()
                        .HasForeignKey("IdCitizen")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("eVote360.Core.Domain.Entities.Election.Election", "ElectionEntities")
                        .WithMany()
                        .HasForeignKey("IdElection")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Citizens");

                    b.Navigation("ElectionEntities");
                });

            modelBuilder.Entity("eVote360.Core.Domain.Entities.Elector.CodeVerifications.CodeVerification", b =>
                {
                    b.HasOne("eVote360.Core.Domain.Entities.Citizens.Citizen", "Citizen")
                        .WithMany()
                        .HasForeignKey("IdCitizens")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("eVote360.Core.Domain.Entities.Election.Election", "election")
                        .WithMany()
                        .HasForeignKey("IdElection")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Citizen");

                    b.Navigation("election");
                });

            modelBuilder.Entity("eVote360.Core.Domain.Entities.Elector.Vote.Votes", b =>
                {
                    b.HasOne("eVote360.Core.Domain.Entities.Candidate.Candidates", null)
                        .WithMany("VotosRecibidos")
                        .HasForeignKey("CandidatesId");

                    b.HasOne("eVote360.Core.Domain.Entities.Citizens.Citizen", null)
                        .WithMany("Vote")
                        .HasForeignKey("CitizenId");

                    b.HasOne("eVote360.Core.Domain.Entities.ElectivePosition.ElectivePositions", null)
                        .WithMany("votes")
                        .HasForeignKey("ElectivePositionsId");

                    b.HasOne("eVote360.Core.Domain.Entities.Candidate.Candidates", "Candidacte")
                        .WithMany()
                        .HasForeignKey("IdCandidate")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("eVote360.Core.Domain.Entities.Election.Election", "Elections")
                        .WithMany("Votes")
                        .HasForeignKey("IdElection")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("eVote360.Core.Domain.Entities.ElectivePosition.ElectivePositions", "ElectivePosition")
                        .WithMany()
                        .HasForeignKey("IdElectivePosiction")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Candidacte");

                    b.Navigation("Elections");

                    b.Navigation("ElectivePosition");
                });

            modelBuilder.Entity("eVote360.Core.Domain.Entities.PoliticalAlliances.PoliticalAlliances", b =>
                {
                    b.HasOne("eVote360.Core.Domain.Entities.PoliticalParty.PoliticalParty", "ReceivingParty")
                        .WithMany("ReceiveAlliances")
                        .HasForeignKey("ReceivingPartyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("eVote360.Core.Domain.Entities.PoliticalParty.PoliticalParty", "RequestingParty")
                        .WithMany("RequestedAlliances")
                        .HasForeignKey("RequestingPartyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ReceivingParty");

                    b.Navigation("RequestingParty");
                });

            modelBuilder.Entity("eVote360.Core.Domain.Entities.PoliticalAssignment.PoliticalAssignment", b =>
                {
                    b.HasOne("eVote360.Core.Domain.Entities.User.User", "UserCreate")
                        .WithMany()
                        .HasForeignKey("CreateUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("eVote360.Core.Domain.Entities.User.User", "PoliticalLeader")
                        .WithMany("PoliticalAssignments")
                        .HasForeignKey("PoliticalLeaderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("eVote360.Core.Domain.Entities.PoliticalParty.PoliticalParty", "PoliticalParty")
                        .WithMany("Assignments")
                        .HasForeignKey("PoliticalPartyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("eVote360.Core.Domain.Entities.User.User", "UserUpdate")
                        .WithMany()
                        .HasForeignKey("UpdateUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("PoliticalLeader");

                    b.Navigation("PoliticalParty");

                    b.Navigation("UserCreate");

                    b.Navigation("UserUpdate");
                });

            modelBuilder.Entity("eVote360.Core.Domain.Entities.PoliticalParty.PoliticalParty", b =>
                {
                    b.HasOne("eVote360.Core.Domain.Entities.User.User", "UserCreate")
                        .WithMany()
                        .HasForeignKey("CreateUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("eVote360.Core.Domain.Entities.User.User", "UserUpdate")
                        .WithMany()
                        .HasForeignKey("UpdateUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.OwnsOne("eVote360.Core.Domain.Settings.ValueObjects.Candidate.CandidatePhoto", "PoliticalPartyLogo", b1 =>
                        {
                            b1.Property<int>("PoliticalPartyId")
                                .HasColumnType("int");

                            b1.Property<string>("PhotoUrl")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("PoliticalPartyLogo");

                            b1.HasKey("PoliticalPartyId");

                            b1.ToTable("PoliticalParties");

                            b1.WithOwner()
                                .HasForeignKey("PoliticalPartyId");
                        });

                    b.OwnsOne("eVote360.Core.Domain.Settings.ValueObjects.PoliticalPartyAcronym.PoliticalPartyAcronym", "PoliticalPartyAcronym", b1 =>
                        {
                            b1.Property<int>("PoliticalPartyId")
                                .HasColumnType("int");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("nvarchar(450)")
                                .HasColumnName("PoliticalPartyAcronym");

                            b1.HasKey("PoliticalPartyId");

                            b1.HasIndex("Value")
                                .IsUnique();

                            b1.ToTable("PoliticalParties");

                            b1.WithOwner()
                                .HasForeignKey("PoliticalPartyId");
                        });

                    b.Navigation("PoliticalPartyAcronym")
                        .IsRequired();

                    b.Navigation("PoliticalPartyLogo")
                        .IsRequired();

                    b.Navigation("UserCreate");

                    b.Navigation("UserUpdate");
                });

            modelBuilder.Entity("eVote360.Core.Domain.Entities.User.User", b =>
                {
                    b.OwnsOne("eVote360.Core.Domain.Settings.ValueObjects.Emails.Email", "UserEmail", b1 =>
                        {
                            b1.Property<int>("UserId")
                                .HasColumnType("int");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar")
                                .HasColumnName("Email");

                            b1.HasKey("UserId");

                            b1.HasIndex("Value")
                                .IsUnique();

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsOne("eVote360.Core.Domain.Settings.ValueObjects.UserPassword.UserPassword", "UserPassword", b1 =>
                        {
                            b1.Property<int>("UserId")
                                .HasColumnType("int");

                            b1.Property<string>("HashValue")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("PasswordHash");

                            b1.HasKey("UserId");

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.Navigation("UserEmail")
                        .IsRequired();

                    b.Navigation("UserPassword")
                        .IsRequired();
                });

            modelBuilder.Entity("eVote360.Core.Domain.Entities.Candidate.Candidates", b =>
                {
                    b.Navigation("AsignacionesPuestos");

                    b.Navigation("VotosRecibidos");
                });

            modelBuilder.Entity("eVote360.Core.Domain.Entities.Citizens.Citizen", b =>
                {
                    b.Navigation("AuditVote");

                    b.Navigation("Vote");
                });

            modelBuilder.Entity("eVote360.Core.Domain.Entities.Election.Election", b =>
                {
                    b.Navigation("AuditVotes");

                    b.Navigation("ElectivePositions");

                    b.Navigation("Votes");
                });

            modelBuilder.Entity("eVote360.Core.Domain.Entities.ElectivePosition.ElectivePositions", b =>
                {
                    b.Navigation("CandidateAssignments");

                    b.Navigation("votes");
                });

            modelBuilder.Entity("eVote360.Core.Domain.Entities.PoliticalParty.PoliticalParty", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("Candidates");

                    b.Navigation("ReceiveAlliances");

                    b.Navigation("RequestedAlliances");
                });

            modelBuilder.Entity("eVote360.Core.Domain.Entities.User.User", b =>
                {
                    b.Navigation("PoliticalAssignments");
                });
#pragma warning restore 612, 618
        }
    }
}
